### PR TITLE
Prevent namespace collisions

### PR DESCRIPTION
**Pull request by dustinlarimer**
## What does this PR do?

This PR updates the Keen IO integration to mitigate the potential for namespace collisions when using other versions of Keen SDKs.
- Create a new `KeenSegment` namespace for analytics.js-installed SDK and restore existing `Keen` object if overwritten
- Update keen-js to v3.1.0 (latest possible without breaking changes)
- Version bump to v1.0.5

### CODE REVIEW

**Comment by dustinlarimer** [comment]
Disregard the extensive commit message from my last commit 😁 Including `Keen` with tick marks in the commit message seems to have invoked the Keen CLI's help text- ha!

**Comment by dustinlarimer** [comment]
@hankim813 this PR will resolve our ongoing issues with the underlying SDK being out of date, which primarily affects those who want to use our latest data visualization and analysis SDKs. Now a dev can manually install any of our other modules (synchronously) and this integration will gracefully restore the `Keen` namespace after initialization. I also added a few tests to ensure this works as expected.

**Comment by joannecheng** [comment]
screen shot 2016-05-24 at 5 08 05 pm

I'm getting a few errors when I run `npm test`

**Comment by joannecheng** [comment]
I'm getting a few warnings when I run `npm test` related to some of the code you added to `index.js`

screen shot 2016-05-24 at 5 08 05 pm

**Comment by dustinlarimer** [comment]
Make sure to run v0.12 of node. I hit those issues as well, and they appear to be environmental.

**Pull request merged**
